# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    config_metallb.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tor <tor@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/07 18:49:42 by tor               #+#    #+#              #
#    Updated: 2021/01/18 22:35:57 by tor              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.49.10-192.168.49.10