# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    namespace.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tor <tor@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/07 18:22:09 by tor               #+#    #+#              #
#    Updated: 2021/01/07 18:40:36 by tor              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app: metallb