# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    service_mysql.yaml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tor <tor@student.42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/18 14:16:40 by tor               #+#    #+#              #
#    Updated: 2021/01/20 16:42:37 by tor              ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      run: mysql
  template:
    metadata:
      labels:
        run: mysql
    spec:
      containers:
      - name: mysql
        image: bestmysql
        imagePullPolicy : Never
        ports:
        - containerPort: 3306
